version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my123password
      POSTGRES_DB: periferia_RR_SS
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
